### ISSUE TITLE
Various minor corrections

### ISSUE THREAD

**Issue by nathaneastwood** [jozefhajnala/sparkfromr#5]
Hi Jozef, I found a few minor issues with the book.

* There is sometimes use of _dplyr_ and other times dplyr (for various package names)
* We could certainly figure our a way to fix this particular issue, but the workarounds may prove inefficient: <- Should be figure "out"
* When using the pipe, I personally feel that each call should be on its own line if it is a multiline expression. Sometimes this isn't the case. Single line expressions are fine, i.e. `mtcars %>% select(mpg)` (check out the first code block in section 9.2 as an example of what I mean).
* Let us write a small wrapper that will return a some <- no need for the a (Section 10.3)
* Now that the setup is complete, we use the _dplyr_ verb approach to retrieve the count of rows and look the invocations that this entails. <- Missing an at "...and look at" (Section 10.4.1)
* We see multiple invocations do the < - "to the" (Section 10.4.1)

Also, the wrappers you have written in Section 10 for exploring the java objects are great - you should package them up! Also a neat idea could be to then write a function which would take you to the help page of a scala method. Something like `scala_help("getAll")` I suspect you could build the link programatically. If you do this, let me know if you'd like to collaborate.

Overall a very, very good read - I really enjoyed it. It's really well written and flows nicely. There's an incredible amount of content in a small book. Kudos Jozef!

**Comment by jozefhajnala** [comment]
Many thanks for such constructive feedback! Will implement.
